CREATE TABLE IF NOT EXISTS roles (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS readers (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(30) NOT NULL,
password VARCHAR(80) NOT NULL
);

CREATE TABLE IF NOT EXISTS readers_roles (
reader_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
FOREIGN KEY (reader_id) REFERENCES readers (id),
FOREIGN KEY (role_id) REFERENCES roles (id)
);