server:
  port: 3000
  servlet:
    context-path: /lib-front

spring:
  application:
    name: front-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

integrations:
  reader-service:
    connect-timeout: 5000
    read-timeout: 25000
    write-timeout: 5000

starter-aspect:
  properties:
    enabled: true
    log-level: info