CREATE TABLE IF NOT EXISTS books (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
author VARCHAR(100) NOT NULL,
name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS issues (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
book_id BIGINT REFERENCES books (id),
reader VARCHAR(100),
date_of_issue TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_of_return TIMESTAMP
);
