CREATE TABLE IF NOT EXISTS books (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
author VARCHAR(50) NOT NULL,
name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS roles (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS readers (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(50) NOT NULL,
password VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS readers_roles (
reader_id BIGINT NOT NULL,
role_id BIGINT NOT NULL,
FOREIGN KEY (reader_id) REFERENCES readers (id),
FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS issues (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
book_id BIGINT REFERENCES books (id),
reader_id BIGINT REFERENCES readers (id),
date_of_issue TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_of_return TIMESTAMP
);
