CREATE TABLE IF NOT EXISTS books (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
author VARCHAR(255) NOT NULL,
name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS readers (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS issues (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
book_id BIGINT REFERENCES books (id),
reader_id BIGINT REFERENCES readers (id),
date_of_issue TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
date_of_return TIMESTAMP
);
