server:
  port: 8191
  servlet:
    context-path: /lib-reader

spring:
  application:
    name: reader-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library-readers
    username: root
    password: EY9fhJLjXok5TQ%
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  mysql:
    console:
      enabled: true
      settings:
        web-allow-others: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka